baseurl: '/'
languageCode: en-us
defaultContentLanguage: en
isMultilingual: false
title: "Alexander Trost aka galexrt"
theme: sam
pygmentsStyle: dracula
pygmentsCodefences: true
params:
  dateform: 'Mon Jan 02, 2006'
  dateformfull: 'Mon Jan 02 2006 15:04:05 EST'
  favicon: favicon.png
  homepage: main
  footerText: '[Impressum](/site-notice/) | [Privacy Policy](/privacy-policy/) | Copyright (c) Alexander Trost 2021'
  description: "Alexander Trost aka galexrt homepage."
  images:
    # TODO Use higher resolution custom social share (opengraph) image
    - favicon.png
  title: Alexander Trost
  videoBackground:
    sources:
      - source: /video1_rescaled_QWXGA_20fps_cut_low.webm
        type: video/mp4
        poster: /background.jpg
    overlay: 'rgba(0, 0, 0, 0.75)'
  mainMenu:
    - link: about
      text: about
    - link: projects
      text: projects
    - link: setup
      text: setup
    - link: https://edenmal.moe/
      text: blog
    - link: https://docs.galexrt.moe/
      text: docs
imaging:
  quality: 75
markup:
  goldmark:
    renderer:
      unsafe: true
